### ISSUE TITLE
Error after upgrading 

### ISSUE THREAD

**Issue by valeriy67** [ncstate-delta/moodle-mod_zoom#228] opened 2021-03-12 09:09 UTC
Hello!
After upgrading to the latest version of Zoom. I get an error:
Zoom received a bad request: Only available for Paid account.
Moodle 3.9.
Thank you!

**Comment by jrchamp** [comment] 2021-04-26 18:55
Does an older version of the plugin still work for you? The string "Only available for Paid account" is coming from Zoom's API, not from this plugin. #251 is likely a duplicate of this issue.

**Comment by jrchamp** [comment] 2021-07-08 15:21
If you get a chance to compare the versions and only the newer versions are not working, please feel free to re-open this issue. For now, I'll mark this as closed.

**Comment by nickchen** [comment] 2021-10-01 04:17
possibly related, https://devforum.zoom.us/t/code-200-no-permission-on-account-user-settings-request/42859/4 .

**Comment by jrchamp** [comment] 2021-10-08 02:36
Thank @nickchen, it looks like the [account settings API call](https://marketplace.zoom.us/docs/api-reference/zoom-api/accounts/accountsettings) was added in https://github.com/ncstate-delta/moodle-mod_zoom/commit/f35bc6782285b4bd9be0882c26c02cb1977a0202 which was released on March 10 with v3.5. It looks like the try/catch are catching exceptions and then immediately throwing them again. Instead, when there's an exception, the code should probably be falling back gracefully to reasonable defaults.

**Comment by jrchamp** [comment] 2021-12-09 16:27
Hopefully can use the defaults from:
https://github.com/ncstate-delta/moodle-mod_zoom/blob/9f99437ac919a4c05df5c604dd2d34f434918607/classes/webservice.php#L426-L439

**Comment by smbader** [comment] 2022-03-31 15:33
Instead of throwing a moodle_exception, initialize meeting_security to good defaults and return that instead. 

meeting_password_requirement and end_to_end_encrypted_meetings may be the only thing needed set.

**Closed** 2022-05-19 15:22 UTC
Labels: bug
